# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images/default_avatar.jpg', upload_to='avatars', verbose_name='фото'),
        ),
    ]
