# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170416_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.jpg', upload_to='avatars', verbose_name='фото'),
        ),
    ]
