# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 10:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170416_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('confirmed_date', models.DateTimeField(blank=True, null=True, verbose_name='дата подтверждения')),
                ('confirmed', models.BooleanField(default=False, verbose_name='подтверждение')),
            ],
            options={
                'verbose_name_plural': 'подтверждения аккаунтов',
                'verbose_name': 'подтверждение аккаунта',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='подтверждение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail address'),
        ),
        migrations.AddField(
            model_name='accountvalidation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
