# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 21:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20170314_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.Chat', verbose_name='чат'),
        ),
        migrations.AlterField(
            model_name='userchat',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='chat.Chat', verbose_name='чат'),
        ),
        migrations.AlterField(
            model_name='userchat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userchats', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
