# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 01:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achieve',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achieve',
            name='title',
            field=models.CharField(default=None, max_length=128, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default=None, max_length=128, verbose_name='заголовок'),
        ),
    ]
